@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.example.website.Utils#hashPassword(String,byte[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.example.website.Utils",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1622542313 { 
   	label=website
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1584103267 { 
   	label=AdminController
	labeljust=l
	fillcolor=white
	style=filled
   
   AdminController615317920XXXaddUser1948773266[
	label="+ addUser()"
	style=filled
	fillcolor=white
	tooltip="AdminController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1676641077 { 
   	label=UserController
	labeljust=l
	fillcolor=white
	style=filled
   
   UserController615317920XXXchangePassword515122812[
	label="+ changePassword()"
	style=filled
	fillcolor=white
	tooltip="UserController

null"
	fontcolor=darkgreen
];

UserController615317920XXXlogin73596745[
	label="+ login()"
	style=filled
	fillcolor=white
	tooltip="UserController

null"
	fontcolor=darkgreen
];

UserController615317920XXXregister1948773266[
	label="+ register()"
	style=filled
	fillcolor=white
	tooltip="UserController

null"
	fontcolor=darkgreen
];

UserController615317920XXXregisterAdmin1948773266[
	label="+ registerAdmin()"
	style=filled
	fillcolor=white
	tooltip="UserController

null"
	fontcolor=darkgreen
];

UserController615317920XXXregisterEmployee1948773266[
	label="+ registerEmployee()"
	style=filled
	fillcolor=white
	tooltip="UserController

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1937987507 { 
   	label=UserService
	labeljust=l
	fillcolor=white
	style=filled
   
   UserService1927363983XXXchangePassword924985979[
	label="+ changePassword()"
	style=filled
	fillcolor=white
	tooltip="UserService

null"
	fontcolor=darkgreen
];

UserService1927363983XXXlogin73596745[
	label="+ login()"
	style=filled
	fillcolor=white
	tooltip="UserService

null"
	fontcolor=darkgreen
];

UserService1927363983XXXregister1948773266[
	label="+ register()"
	style=filled
	fillcolor=white
	tooltip="UserService

null"
	fontcolor=darkgreen
];

UserService1927363983XXXregisterAdmin1948773266[
	label="+ registerAdmin()"
	style=filled
	fillcolor=white
	tooltip="UserService

null"
	fontcolor=darkgreen
];

UserService1927363983XXXregisterEmployee1948773266[
	label="+ registerEmployee()"
	style=filled
	fillcolor=white
	tooltip="UserService

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_2004690099 { 
   	label=Utils
	labeljust=l
	fillcolor=white
	style=filled
   
   Utils1140340138XXXhashPassword1847790577[
	label="+ hashPassword()"
	style=filled
	fillcolor=white
	tooltip="Utils

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
AdminController615317920XXXaddUser1948773266 -> UserService1927363983XXXregisterAdmin1948773266;
AdminController615317920XXXaddUser1948773266 -> UserService1927363983XXXregisterEmployee1948773266;
UserController615317920XXXchangePassword515122812 -> UserService1927363983XXXchangePassword924985979;
UserController615317920XXXlogin73596745 -> UserService1927363983XXXlogin73596745;
UserController615317920XXXregister1948773266 -> UserService1927363983XXXregister1948773266;
UserController615317920XXXregisterAdmin1948773266 -> UserService1927363983XXXregisterAdmin1948773266;
UserController615317920XXXregisterEmployee1948773266 -> UserService1927363983XXXregisterEmployee1948773266;
UserService1927363983XXXchangePassword924985979 -> Utils1140340138XXXhashPassword1847790577;
UserService1927363983XXXlogin73596745 -> Utils1140340138XXXhashPassword1847790577;
UserService1927363983XXXregister1948773266 -> Utils1140340138XXXhashPassword1847790577;
UserService1927363983XXXregisterAdmin1948773266 -> Utils1140340138XXXhashPassword1847790577;
UserService1927363983XXXregisterEmployee1948773266 -> Utils1140340138XXXhashPassword1847790577;
    
}
@enduml